# Generated by Django 6.0.5 on 2026-05-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='veces_impreso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
