# Generated by Django 6.0.5 on 2026-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_pedido_veces_impreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='comanda_etiqueta',
            field=models.CharField(blank=True, default='', help_text='Texto en el encabezado de la comanda. Ej: COCINA, BEBIDAS.', max_length=50, verbose_name='Etiqueta de comanda'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='comanda_sufijo',
            field=models.CharField(blank=True, default='', help_text='Ej: C, B, CH. Categorías con el mismo sufijo van en la misma comanda. Vacío = sin comanda.', max_length=10, verbose_name='Sufijo de comanda'),
        ),
    ]
