# Generated by Django 5.2.14 on 2026-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_pedido_veces_impreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto recibido'),
        ),
    ]
